name: Deploy to GitHub Releases

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' PinayPalBackupManager.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Publish Application
        run: dotnet publish PinayPalBackupManager.csproj -c Release -o publish -r win-x64 --self-contained true

      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
          vpk pack -u PinayPal.PinayPalBackupManager -v ${{ steps.get-version.outputs.version }} -p publish --mainExe PinayPalBackupManager.exe --icon Assets/logo.ico
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "PinayPalBackupManager ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN }}
